"""add ocr_status to files

Revision ID: 599e9c12a708
Revises: 9ed0676e0b81
Create Date: 2026-08-27 17:30:16.178802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599e9c12a708'
down_revision: Union[str, Sequence[str], None] = '9ed0676e0b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('ocr_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'ocr_status')
    # ### end Alembic commands ###
