"""add entities auto_tags and source_file_id to notes

Revision ID: 66953fd2a718
Revises: 6aacae8e72f3
Create Date: 2026-09-06 19:16:43.125396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66953fd2a718'
down_revision: Union[str, Sequence[str], None] = '6aacae8e72f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('entities', sa.JSON(), nullable=True))
    op.add_column('notes', sa.Column('auto_tags', sa.JSON(), nullable=True))
    op.add_column('notes', sa.Column('source_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'files', ['source_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'source_file_id')
    op.drop_column('notes', 'auto_tags')
    op.drop_column('notes', 'entities')
    # ### end Alembic commands ###
