"""add entities JSON column to file_attachments

Revision ID: 6aacae8e72f3
Revises: a9b3ce08af70
Create Date: 2026-09-06 09:35:50.357949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aacae8e72f3'
down_revision: Union[str, Sequence[str], None] = 'a9b3ce08af70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
