"""add extracted_text to files

Revision ID: 860389bd8d05
Revises: 599e9c12a708
Create Date: 2026-08-27 19:36:18.778068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860389bd8d05'
down_revision: Union[str, Sequence[str], None] = '599e9c12a708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'extracted_text')
    # ### end Alembic commands ###
