"""add entities column to file_attachments

Revision ID: a9b3ce08af70
Revises: 860389bd8d05
Create Date: 2026-09-03 09:57:47.568766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b3ce08af70'
down_revision: Union[str, Sequence[str], None] = '860389bd8d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('entities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'entities')
    # ### end Alembic commands ###
